### ISSUE TITLE
Locations Not Appearing in Dropdown - WE - High

### ISSUE THREAD

**Issue by Happs80** [humansis/front#169]
![image](https://user-images.githubusercontent.com/31128624/71800407-261a7e00-30ac-11ea-95e5-798399bc7d68.png)

**Comment by chivy-we** [comment]
@Happs80 This issue is caused from the API, should be move it to https://github.com/humansis/api/issues?

We need to run the command `php bin/console doctrine:fixtures:load --append --group=location` via the deployment to re-import the location files at `https://github.com/humansis/api/tree/dev/src/CommonBundle/DataFixtures/LocationFiles`

**Comment by chivy-we** [comment]
https://github.com/humansis/api/pull/9

**Comment by Happs80** [comment]
API Issue.
